server:
  port: 8083

spring:
  application:
    name: routing-service
  neo4j:
    uri: ${NEO4J_URI:bolt://neo4j:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD}